---
version: "3"
services:
 devopsdb:
   image: arunb999/automate:db
   ports:
     - "3306:3306"
  
 application:
   image: arunb999/automate:app
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
